### ISSUE TITLE
Static linux binaries

### ISSUE THREAD

**Issue by darles** [h4cc/wkhtmltoimage-amd64#5]
Is it possible to solve same problem here as it was in wkhtmltopdf?

https://github.com/wkhtmltopdf/wkhtmltopdf/issues/1822

**Comment by h4cc** [comment]
What do you mean exactly? Please elaborate the "problem".

**Comment by darles** [comment]
Everything is working with 1.12.0 (but it add noise on transparent png background). With 1.12.2.1 & 1.12.1 versions I get an error:
"/vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory"

All libs are installed.
OS: Amazon Linux AMI 2015.09

**Comment by h4cc** [comment]
Yep, thats the problem @ashkulz explained. Since __0__.12.1 there is a build for each distribution and version out there, like Ubuntu, Debian, etc. Because a pure static linked binary had its own problems, that it did not work everywhere.

This repository is not abled to provide the new wkhtml* binaries, __only for Debian 7.8 (Wheezy)__ as stated in the readme.
If you need these binaries and do not use Debian 7.8 (Wheezy), simply install the wkhtml* package on the machine or instance.

**Comment by darles** [comment]
Thanks!

**Comment by dilab** [comment]
So @darles , what did  you end up doing? I am facing the same issue. 

I am no sure which distro version of the binary I should be using

**Comment by h4cc** [comment]
@dilab Since wkhtmltox version __0.12.3__ there are static binaries again, not special for any distribution: http://wkhtmltopdf.org/downloads.html
Check this release: https://github.com/h4cc/wkhtmltoimage-amd64/releases/tag/0.12.3

**Comment by martin-koroudjiev** [comment]
@h4cc On the download page, it says the generic version depends on X 11 libs. The hosting provider doesn't have them. Is there a *pure* static version?

**Comment by h4cc** [comment]
This is just a repository for providing the binaries. There are no other binaries than on the download page.

Questions about compatibility can only be asked at the project: https://github.com/wkhtmltopdf/wkhtmltopdf
